{
	"name": "Testovanie",
	"version": "16.0",
	"author": "Pato Dovicovic",
	"summary": "Place your summary in here",
	"description": "Place your description in here. Feel free to contact me +6287731588137",
	"data": [
		"views/sdm_player.xml",
		"views/sdm_season.xml",
		"views/sdm_testing.xml",
		"views/sdm_discipline.xml",
		"views/sdm_team.xml",
		"views/sdm_test.xml",
		"views/sdm_testingresult.xml",
		"views/sdm_statistic.xml",
		"views/menu.xml",
		"security/security.xml",
		"security/ir.model.access.csv",
	],
	"depends": [ "sdm_respartner","mail","contacts"],
	"external_dependencies": {"python" : ["numpy"]},
	"installable": True,
	"application": True,
	"license": "AGPL-3",
}