
version: '2'

services:
  web:
    image: odoo:16.0
    entrypoint: ["odoo", "-c", "/etc/odoo/odoo.conf","-u","testovanie"]
    depends_on:
      - db
    ports:
      - "8050:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
 
volumes:
  odoo-web-data:
  odoo-db-data:
