
version: '2'

services:
  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    entrypoint: ["odoo", "-c", "/etc/odoo/odoo.conf","-u","testovanie,sdm_respartner",]
    depends_on:
      - db
    ports:
      - "8050:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    ports:
      - "19530:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

volumes:
  odoo-web-data:
  odoo-db-data:

